### ISSUE TITLE
SCP-079 - Going AFK breaks hacking changes

### ISSUE THREAD

**Issue by McYeke** [civilnetworks/SCP_Public_Development#281] opened 2022-12-20 22:28 UTC
Description: when a player goes AFK as SCP-079 and gets their items back, the TE-5 breaks and the user can no longer silent hack, and the difficulty scaling ceases to work with SCP-079.

Replication: 
- Play as SCP-079
- Go AFK (Items culled)
- Return back to game and get items back
- hack anything, difficulty scaling and quiet hacking is gone.

**Comment by cloakical** [comment] 2023-01-02 13:03
Duplicate of https://github.com/civilnetworks/SCP_Private_Development/issues/272 - please check more carefully before creating tickets

**Closed by cloakical** 2023-01-02 13:03 UTC
Labels: bug
